import examData from '../data.json'
import { Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import type { PassRate } from '../types'
const cssVar = (name: string) => getComputedStyle(document.documentElement).getPropertyValue(name).trim()
export function PassRateStrip({ rates }: { rates: PassRate[] }) {
  const recent = rates.slice(0, 3).reverse()
  if (!recent.length) return <section className="pass-rate-strip empty-rate"><div><span className="eyebrow">RECENT PASS RATES</span><h2>최근 3개 회차 합격률</h2><p>확인된 합격률 자료가 아직 없습니다.</p><small>{examData.passRates.asOf} 기준 · 출처 <a href={examData.passRates.source.url} target="_blank" rel="noreferrer">{examData.passRates.source.name}</a></small></div></section>
  const data = recent.map((item) => ({ name: `${String(item.year).slice(2)}년 ${item.round}회`, rate: item.rate }))
  return <section className="pass-rate-strip" aria-labelledby="recent-rate-title"><div className="pass-rate-heading"><span className="eyebrow">RECENT PASS RATES</span><h2 id="recent-rate-title">최근 3개 회차 합격률</h2><p>합격인원 ÷ 응시인원 × 100</p><small>{examData.passRates.asOf} 기준 · 출처 <a href={examData.passRates.source.url} target="_blank" rel="noreferrer">{examData.passRates.source.name}</a></small></div><div className="pass-rate-scroll"><div className="rate-chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={data} margin={{ top: 18, right: 16, bottom: 0, left: -24 }}><XAxis dataKey="name" tick={{ fontSize: 11 }} axisLine={false} tickLine={false} /><YAxis unit="%" domain={[0, 100]} tick={{ fontSize: 11 }} axisLine={false} tickLine={false} /><Tooltip formatter={(value: number) => [`${value}%`, '합격률']} /><Line type="monotone" dataKey="rate" stroke={cssVar('--chart-1')} strokeWidth={3} dot={{ r: 5, fill: cssVar('--block-yellow'), stroke: cssVar('--color-border-strong'), strokeWidth: 2 }} activeDot={{ r: 7 }} /></LineChart></ResponsiveContainer></div><div className="rate-cards">{recent.map((item) => <article className="rate-card" key={item.id}><span>{item.year}년 {item.round}회차</span><strong className="tabular">{item.rate}%</strong><small>응시 {item.applicants.toLocaleString()} · 합격 {item.passers.toLocaleString()}</small></article>)}</div></div></section>
}
