import { api } from '../lib/api'
import { useEffect, useState } from 'react'
import type { ExamType, Question } from '../types'
export function QuestionEditor({ question, year, examType, onClose, onSaved, onDeleted }: { question?:Question; year:number; examType:ExamType; onClose:()=>void; onSaved:()=>void; onDeleted:()=>void }) {
 const [form,setForm]=useState({year:String(question?.year||year),question:question?.question||'',answer:question?.answer||''}); const [error,setError]=useState(''); const [busy,setBusy]=useState(false)
 useEffect(()=>setForm({year:String(question?.year||year),question:question?.question||'',answer:question?.answer||''}),[question,year])
 const save=async()=>{if(!form.question.trim()||!form.answer.trim()){setError('문제와 정답은 꼭 입력해 주세요.');return}setBusy(true);try{const res=await api(`questions${question?`/${question.id}`:''}`,{method:question?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,year:Number(form.year),exam_type:examType})});if(!res.ok)throw new Error();onSaved()}catch{setError('저장하지 못했어요. 내용을 다시 확인해 주세요.')}finally{setBusy(false)}}
 const remove=async()=>{if(!question||!confirm('이 문제를 삭제할까요?'))return; const response=await api(`questions/${question.id}?exam_type=${examType}`,{method:'DELETE'});if(response.ok)onDeleted();else setError('삭제하지 못했어요. 잠시 후 다시 시도해 주세요.')}
 return <div className="modal-backdrop" role="presentation"><section className="editor-modal" role="dialog" aria-modal="true" aria-label="문제 편집"><div className="modal-head"><h2>{question?'문제 수정':'문제 추가'}</h2><button className="icon-button" onClick={onClose}>×</button></div><div className="photo-notice" role="note"><b>사진 첨부 안내</b><p>앱 사용자가 문제 사진을 직접 올리는 기능은 현재 지원하지 않아요. 필요한 예시 사진은 제작 시 미리 넣어 둘 수 있으니, 반영할 사진을 채팅에 첨부해 주세요.</p></div><label>출제 연도<select value={form.year} onChange={e=>setForm({...form,year:e.target.value})}>{Array.from({length:15},(_,i)=><option key={i} value={2012+i}>{2012+i}년</option>)}</select></label><label>문제 문구<textarea value={form.question} onChange={e=>setForm({...form,question:e.target.value})} placeholder="단답형 문제를 입력하세요&#10;줄바꿈도 그대로 표시됩니다" /></label><label>정답<textarea value={form.answer} onChange={e=>setForm({...form,answer:e.target.value})} placeholder="모범 답안을 입력하세요" /></label>{error&&<p className="form-error">{error}</p>}<div className="modal-actions">{question&&<button className="danger-text" onClick={remove}>삭제</button>}<span/><button className="secondary press" onClick={onClose}>취소</button><button className="primary press" onClick={save} disabled={busy}>{busy?'저장 중':'저장하기'}</button></div></section></div>
}
