import type { Filter, Question } from '../types'
const filters: Array<[Filter, string]> = [['all','전체'], ['unlearned','미학습'], ['starred','★ 별표'], ['difficult','오답 많은'], ['mastered','암기 완료']]
export function QuestionList({ year, questions, filter, isAdmin, onFilter, onStudy, onPractice, onEdit, onReset, onToggleStar, onToggleMaster }: { year:number; questions:Question[]; filter:Filter; isAdmin:boolean; onFilter:(f:Filter)=>void; onStudy:()=>void; onPractice:()=>void; onEdit:(q?:Question)=>void; onReset:(target:'answers'|'wrongs')=>void; onToggleStar:(q:Question)=>void; onToggleMaster:(q:Question)=>void }) {
 return <section className="manage-page"><header className="section-head"><div><span className="eyebrow">{year}년 {isAdmin ? '· 관리자 모드' : ''}</span><h2>{isAdmin ? '공통 문제 관리' : '문제 학습'}</h2><p>총 {questions.length}개 문제가 현재 조건에 표시됩니다.</p></div><div className="head-actions">{isAdmin ? <div className="progress-reset-actions"><button className="secondary press" onClick={()=>onEdit()}>＋ 문제 추가</button></div> : <><div className="progress-reset-actions"><button className="secondary press" disabled={!questions.length} onClick={()=>onReset('answers')}>답안 초기화</button><button className="secondary press" disabled={!questions.length} onClick={()=>onReset('wrongs')}>오답 초기화</button></div><div className="study-start-actions"><button className="secondary practice-start press" disabled={!questions.length} onClick={onPractice}>답과 함께 연습 시작 →</button><button className="primary press" disabled={!questions.length} onClick={onStudy}>학습 시작 →</button></div></>}</div></header>
 <aside className="management-notice" role="note"><b>{isAdmin ? '공통 문제 안내' : '학습 기록 안내'}</b><p>{isAdmin ? <>관리자가 추가·수정·삭제한 문제는 모든 학습 번호에 같은 내용으로 표시됩니다. 앱 사용자의 사진 업로드는 지원하지 않으며, 반영할 사진은 채팅에 첨부해 주세요.</> : <>문제는 공통 목록으로 제공되며, 나의 답안·별표·암기 완료·오답 기록은 현재 로그인한 번호에만 저장됩니다.</>}</p></aside>
 <nav className="filter-bar" aria-label="문제 필터">{filters.map(([key,label])=><button className={filter===key?'active':''} onClick={()=>onFilter(key)} key={key}>{label}</button>)}</nav>
 {!questions.length ? <div className="empty"><b>아직 표시할 문제가 없어요.</b><p>{isAdmin ? '첫 공통 문제를 추가해 보세요.' : '관리자가 문제를 등록하면 여기에서 학습할 수 있어요.'}</p>{isAdmin&&<button className="primary press" onClick={()=>onEdit()}>첫 문제 추가</button>}</div> : <div className="question-list">{questions.map((q,index)=><article className="question-row" key={q.id}><span className="q-index">{String(index+1).padStart(2,'0')}</span><div className="q-body"><p>{q.question}</p>{!isAdmin&&<div className="chips">{q.starred&&<span className="chip star">★ 별표</span>}{q.mastered&&<span className="chip success">암기 완료</span>}{q.wrong_count>=2&&<span className="chip danger">오답 {q.wrong_count}회</span>}</div>}</div><div className="row-actions">{isAdmin ? <button className="mini press" onClick={()=>onEdit(q)}>수정</button> : <><button aria-label="별표 전환" className="icon-button press" onClick={()=>onToggleStar(q)}>{q.starred?'★':'☆'}</button><button className="mini press" onClick={()=>onToggleMaster(q)}>{q.mastered?'완료 취소':'암기 완료'}</button></>}</div></article>)}</div>}
 </section>
}
