import { useCallback, useEffect, useMemo, useState } from 'react'
import examData from './data.json'
import { api } from './lib/api'
import type { ExamSettings, ExamType, Filter, PassRate, Question, Stats, YearSummary } from './types'
import { YearPicker } from './components/YearPicker'
import { QuestionList } from './components/QuestionList'
import { StudyView } from './components/StudyView'
import { QuestionEditor } from './components/QuestionEditor'
import { StatsPage } from './components/StatsPage'
import { DdaySettings } from './components/DdaySettings'
import { LoginGate } from './components/LoginGate'
type Screen = 'years'|'manage'|'study'|'practice'|'review'|'stats'
const examLabels: Record<ExamType, string> = { electric_engineer: '전기기사', electric_construction: '전기공사기사' }
const blankSettings: ExamSettings = { selected_round: null, round_1_date: '', round_2_date: '', round_3_date: '' }
export default function App(){
 const [userPin,setUserPin]=useState<string>(()=>{try{return sessionStorage.getItem('study-user-pin')||''}catch{return ''}})
 const [screen,setScreen]=useState<Screen>('years'),[years,setYears]=useState<YearSummary[]>([]),[questions,setQuestions]=useState<Question[]>([]),[studyQuestions,setStudyQuestions]=useState<Question[]>([]),[year,setYear]=useState(2026),[filter,setFilter]=useState<Filter>('all'),[examType,setExamType]=useState<ExamType>('electric_engineer'),[editor,setEditor]=useState<Question|undefined|false>(false),[stats,setStats]=useState<Stats|null>(null),[settings,setSettings]=useState<ExamSettings>(blankSettings),[rates,setRates]=useState<PassRate[]>([]),[settingsOpen,setSettingsOpen]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[examMenuOpen,setExamMenuOpen]=useState(false)
 const isAdmin=userPin==='0000'
 const handleLogin=(pin:string)=>{try{sessionStorage.setItem('study-user-pin',pin)}catch{};setUserPin(pin)}
 const handleLogout=()=>{try{sessionStorage.removeItem('study-user-pin')}catch{};setUserPin('');setScreen('years');setYears([]);setQuestions([]);setStudyQuestions([]);setStats(null);setSettings(blankSettings);setRates([]);setError('')}
 const examName=examLabels[examType]
 const loadYears=useCallback(async()=>{try{const r=await api(`years?exam_type=${examType}`);if(!r.ok)throw new Error();setYears(await r.json())}catch{setError('학습 정보를 불러오지 못했어요.')}},[examType])
 const loadQuestions=useCallback(async()=>{setLoading(true);try{const r=await api(`questions?exam_type=${examType}&year=${year}&filter=${filter}`);if(!r.ok)throw new Error();setQuestions(await r.json())}catch{setError('문제를 불러오지 못했어요.')}finally{setLoading(false)}},[examType,year,filter])
 const loadStats=useCallback(async()=>{try{const r=await api(`stats?exam_type=${examType}`);if(!r.ok)throw new Error();setStats(await r.json())}catch{setError('현황을 불러오지 못했어요.')}},[examType])
 const loadSettings=useCallback(async()=>{try{const r=await api(`exam-settings?exam_type=${examType}`);if(!r.ok)throw new Error();setSettings(await r.json())}catch{setError('디데이 정보를 불러오지 못했어요.')}},[examType])
 const loadRates=useCallback(async()=>{try{const r=await api(`pass-rates?exam_type=${examType}`);if(!r.ok)throw new Error();setRates(await r.json())}catch{setError('합격률 정보를 불러오지 못했어요.')}},[examType])
 useEffect(()=>{if(!userPin)return;loadYears();loadStats();loadSettings();loadRates()},[userPin,loadYears,loadStats,loadSettings,loadRates]);useEffect(()=>{if(userPin&&(screen==='manage'||screen==='study'||screen==='practice'||screen==='review'))loadQuestions()},[userPin,loadQuestions,screen])
 const selectYear=(choice:number)=>{setYear(choice);setFilter('all');setScreen('manage')}
 const switchExam=(choice:ExamType)=>{setExamType(choice);setYears([]);setQuestions([]);setStats(null);setSettings(blankSettings);setRates([]);setFilter('all');setScreen('years');setExamMenuOpen(false);setError('')}
 const refresh=()=>{loadQuestions();loadYears();loadStats()}
 const toggle=async(id:number,path:'starred'|'mastered',value:boolean)=>{try{const r=await api(`questions/${id}/${path}?exam_type=${examType}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({value})});if(!r.ok)throw new Error();refresh()}catch{setError('변경하지 못했어요.')} }
 const startStudy=(mode:'study'|'practice')=>{setStudyQuestions(questions);setScreen(mode)}
 const resetProgress=async(target:'answers'|'wrongs')=>{const label=target==='answers'?'저장된 나의 답안':'오답 횟수와 오답 기록';if(!confirm(`${year}년 ${examName}의 ${label}을 초기화할까요?`))return;try{const r=await api(`questions/reset?exam_type=${examType}&year=${year}&target=${target}`,{method:'POST'});if(!r.ok)throw new Error();refresh()}catch{setError('초기화하지 못했어요.')}}
 const reviewQuestions=useMemo(()=>questions.filter(q=>q.starred||q.wrong_count>=2),[questions])
 const content=()=>{if(error)return <div className="error-box"><b>{error}</b><button className="secondary press" onClick={()=>{setError('');refresh();loadSettings();loadRates()}}>다시 시도</button></div>;if(screen==='years')return <YearPicker years={years} examType={examType} settings={settings} rates={rates} onChoose={selectYear}/>;if(screen==='stats')return <StatsPage stats={stats} examName={examName} onBack={()=>setScreen('years')}/>;if(screen==='study'||screen==='practice')return <StudyView title={`${year}년 ${examName}`} questions={studyQuestions} initialIndex={0} mode={screen==='practice'?'practice':'test'} onBack={()=>setScreen('manage')} onRefresh={refresh} onPatch={toggle}/>;if(screen==='review')return <StudyView title={`${examName} 별표 · 오답 집중 복습`} questions={reviewQuestions} initialIndex={0} onBack={()=>setScreen('manage')} onRefresh={refresh} onPatch={toggle}/>;return loading?<div className="empty">문제를 불러오고 있어요.</div>:<QuestionList year={year} questions={questions} filter={filter} isAdmin={isAdmin} onFilter={setFilter} onStudy={()=>startStudy('study')} onPractice={()=>startStudy('practice')} onEdit={(q)=>setEditor(q)} onReset={resetProgress} onToggleStar={(q)=>toggle(q.id,'starred',!q.starred)} onToggleMaster={(q)=>toggle(q.id,'mastered',!q.mastered)}/>}
 if(!userPin)return <LoginGate onSuccess={handleLogin}/>
 return <div className="app-shell"><header className="app-header"><div className="brand-switcher" onMouseEnter={()=>setExamMenuOpen(true)} onMouseLeave={()=>setExamMenuOpen(false)}><button className="brand" onClick={()=>setScreen('years')} aria-haspopup="menu" aria-expanded={examMenuOpen}><span>⚡</span> {examName} <b>단답 마스터</b><small>⌄</small></button>{examMenuOpen&&<div className="exam-menu" role="menu" aria-label="시험 선택"><button className={examType==='electric_engineer'?'is-selected':''} onClick={()=>switchExam('electric_engineer')} role="menuitem">전기기사</button><button className={examType==='electric_construction'?'is-selected':''} onClick={()=>switchExam('electric_construction')} role="menuitem">전기공사기사</button></div>}</div><nav><button className={screen==='years'?'nav-active':''} onClick={()=>setScreen('years')}>연도 선택</button><button className="logout-button press" onClick={handleLogout}>나가기</button>{!isAdmin&&<><button className={screen==='review'?'nav-active':''} onClick={()=>setScreen('review')}>집중 복습</button><button className={screen==='stats'?'nav-active':''} onClick={()=>{loadStats();setScreen('stats')}}>학습 현황</button></>}<button className="settings-button" onClick={()=>setSettingsOpen(true)}>설정</button></nav></header><main>{content()}</main><footer className="source-footer"><span>{examData.sources[examType].asOf} 기준 · 출처 <a href={examData.sources[examType].url} target="_blank" rel="noreferrer">{examData.sources[examType].name}</a></span><span>{examData.facts[examType].map((fact)=>`${fact.label}: ${fact.value}`).join(' · ')}</span></footer>{editor!==false&&<QuestionEditor question={editor||undefined} year={year} examType={examType} onClose={()=>setEditor(false)} onSaved={()=>{setEditor(false);refresh()}} onDeleted={()=>{setEditor(false);refresh()}}/>}{settingsOpen&&<DdaySettings examType={examType} settings={settings} rates={rates} isAdmin={isAdmin} onClose={()=>setSettingsOpen(false)} onSaved={setSettings} onRatesChanged={loadRates}/>}</div>
}
